#!/bin/bash

# Create the file
touch '\*\\'"Best School"\'\\*$\?\*\*\*\*\*:)'

# Add the text to the file
echo "Best School" > '\*\\'"Best School"\'\\*$\?\*\*\*\*\*:)'

# Add a new line at the end of the file
echo >> '\*\\'"Best School"\'\\*$\?\*\*\*\*\*:)'

